# Generated by Django 4.1 on 2022-08-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('dob', models.DateField(max_length=50)),
                ('quali', models.CharField(max_length=50)),
                ('hobby', models.CharField(max_length=200)),
                ('objective', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'pt_cv_user',
            },
        ),
    ]
